# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt-test/display.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QGridLayout
from PyQt6.QtCore import QMutex
from typing import List
import functools

from Qt_ui.view_panel.frame_window import frame_win

class Ui_MainWindow(QtWidgets.QWidget):
    def __init__(self, parent, num_cam):
        super().__init__(parent=parent)
        self.num_cam = num_cam
        self.videoWin : List[frame_win] = []
        self.switch_btn_label = False
        self.single_view = False


    def init_figure(self, parent: QtWidgets.QWidget, gpc):
        positions = [(i, j) for i in range(0, 2) for j in range (0, 3)]
        grid = QGridLayout()
        grid.setSpacing(5)
        self.setLayout(grid)

        for i ,p in enumerate(positions):
            thread_params = [i, gpc["frame_pa_conn"][i], gpc["frame_flag"][i], gpc["frame_val4exec_seq"][i], gpc["frame_val4save_pth"][i], QMutex()]
            win = frame_win(parent, gpc["num_channel"][i], i, gpc["frame_buffer"][i], thread_params)
            func = functools.partial(self.single_view_btn_slot, i)
            win.single_view_btn.clicked.connect(func)
            self.videoWin.append(win)
            grid.addWidget(win, *p)  


    def setupUi(self, MainWindow, gpc):
        centralwidget = MainWindow.centralWidget()
        centralwidget.setObjectName("MonitorZone")
        self.init_figure(centralwidget, gpc)

        self.switch_btn = QtWidgets.QPushButton(centralwidget)
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.switch_btn.setFont(font)
        self.switch_btn.setObjectName("switch_btn")
        self.switch_btn.clicked.connect(self.on_clicked)

        self.exitbtn = QtWidgets.QPushButton(centralwidget)
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exitbtn.setFont(font)
        self.exitbtn.setObjectName("exitbtn")
        MainWindow.setCentralWidget(centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.switch_btn.setText(_translate("MainWindow", "Start-Stop"))
        self.exitbtn.setText(_translate("MainWindow", "exit"))


    def on_clicked(self):
        if self.switch_btn_label:
            for win in self.videoWin:
                win.response_main_click_slot()
            self.switch_btn.setText("Start")
            self.switch_btn_label = False
        else:
            for win in self.videoWin:
                win.response_main_click_slot()
            self.switch_btn.setText("Stop")
            self.switch_btn_label = True


    def single_view_btn_slot(self, id: int):
        self.single_view
        for i, win in enumerate(self.videoWin):
            if i == id: continue
            win.single_view_btn.setEnabled(self.single_view)
            win.setVisible(self.single_view)
        
        if self.single_view:
            print("Switched to multi-view")
        else:
            print(f"Switched to single-view of {id}")
        self.single_view = not self.single_view

        